<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}">
<title>{{ $content['meta']['title'] }}</title>
<style>
:root{--bg:#090a0c;--panel:#12151a;--panel2:#191d24;--text:#f4f1e8;--muted:#9198a3;--line:#2c323c;--accent:#efc75e}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% -20%,#2b2112 0,transparent 32rem),var(--bg);color:var(--text);font:14px/1.4 Inter,system-ui,sans-serif}header{position:sticky;top:0;z-index:40;padding:18px max(18px,calc((100vw - 1500px)/2));background:#090a0cf2;backdrop-filter:blur(16px);border-bottom:1px solid var(--line)}
.top{display:flex;justify-content:space-between;gap:18px}.eyebrow{color:var(--accent);font-size:11px;font-weight:800;letter-spacing:.14em}.top h1{font-size:clamp(24px,4vw,42px);line-height:1;margin:5px 0 7px}.sub,.notice{color:var(--muted)}.mode{border:1px solid var(--line);border-radius:99px;padding:7px 11px;height:max-content;white-space:nowrap;color:var(--muted)}.mode.owner{color:#a9e5b0;border-color:#35593a}
.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}input,select,button{background:var(--panel2);color:var(--text);border:1px solid var(--line);border-radius:9px;padding:9px 11px;font:inherit}input{min-width:210px;flex:1}input[type=color]{min-width:72px;height:42px;padding:4px}button{cursor:pointer;font-weight:700}.primary{background:var(--accent);color:#17130a;border-color:var(--accent)}.danger{background:#3b1719;color:#ffb6b6;border-color:#713236}.status{align-self:center;color:var(--muted);font-size:12px}.status.error{color:#ff9292}
main{padding:18px;max-width:1500px;margin:auto}.stats{display:flex;gap:16px;color:var(--muted);margin-bottom:12px}.board{display:grid;gap:9px}.tier{position:relative;display:grid;grid-template-columns:92px 1fr;min-height:126px;background:var(--panel);border:1px solid var(--line);border-radius:12px;overflow:hidden}.label{display:flex;flex-direction:column;align-items:center;justify-content:center;color:#111;font-size:32px;font-weight:950}.label small{font-size:10px;text-align:center;padding:3px 5px;opacity:.68}.tier-actions,.movie-actions{position:absolute;z-index:5;display:flex;gap:5px}.tier-actions{top:8px;right:8px}.movie-actions{top:6px;right:6px}.tier-actions button,.movie-actions button{position:static;width:auto;height:27px;padding:3px 8px;border:1px solid #46505e;border-radius:7px;background:#0b0d10e8;color:#fff;font:700 11px/1 system-ui,sans-serif}.tier-actions .move-tier{width:27px;padding:0;font-size:14px}.tier-actions button:disabled{cursor:default;opacity:.3}.tier-actions .remove-tier,.movie-actions .remove-movie{width:27px;padding:0;color:#ffb7b7;border-color:#6b3538}
.drop{min-height:124px;padding:9px;display:flex;gap:9px;flex-wrap:wrap;align-content:flex-start}.tier>.drop{padding-top:43px}.drop.dragover{outline:2px dashed var(--accent);outline-offset:-6px}.empty{color:#5f6670;margin:auto;font-size:12px}.card{position:relative;width:156px;min-height:104px;padding:12px 12px 46px;background:linear-gradient(145deg,#242a33,#181c22);border:1px solid #363e49;border-radius:10px;box-shadow:0 5px 16px #0004;overflow:hidden}.card:not(.has-poster) .movie-actions{top:auto;bottom:7px}.editor .card{cursor:grab}.card.hidden{display:none}.card.has-poster{padding:0;min-height:210px}.poster{width:100%;height:210px;object-fit:cover}.poster-shade{position:absolute;inset:auto 0 0;padding:35px 10px 10px;background:linear-gradient(transparent,#08090af2)}.title{font-weight:800;line-height:1.25}.meta{font-size:11px;color:#a9b0ba;margin-top:5px}.links{display:flex;gap:12px;flex-wrap:wrap;margin-top:12px}.links a{color:var(--accent);text-decoration:none}.detail-grid{display:flex;gap:16px;align-items:flex-start}.detail-poster{width:160px;max-height:230px;object-fit:cover;border-radius:10px}.unranked{margin-top:18px;border-top:1px solid var(--line);padding-top:16px}.unranked .drop{border:1px dashed #37404c;border-radius:12px;background:#0c0e12;min-height:145px}
.modal{position:fixed;inset:0;z-index:100;background:#000c;display:none;align-items:center;justify-content:center;padding:16px}.modal.on{display:flex}.modalbox{width:min(520px,100%);background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:18px}.modalbox h2{margin:0 0 14px}.modalbox p{color:var(--muted)}.fields{display:grid;gap:10px}.fields input{width:100%}.field-row{display:flex;gap:10px}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}
@media(max-width:700px){header{position:relative}.top{display:block}.mode{display:inline-block;margin-top:11px}.tier{grid-template-columns:60px 1fr}.label{font-size:24px}.card{width:calc(50% - 5px)}.field-row{display:grid}}
</style>
</head>
<body class="{{ $canEdit ? 'editor' : 'viewer' }}" data-can-edit="{{ $canEdit ? 'true' : 'false' }}">
<header><div class="top"><div><div class="eyebrow">MOVIE TIER LIST</div><h1>{{ $content['meta']['title'] }}</h1><div class="sub">{{ $content['meta']['description'] }}</div></div><div class="mode {{ $canEdit ? 'owner' : '' }}">{{ $canEdit ? $content['ui']['owner_mode'] : $content['ui']['viewer_mode'] }}</div></div>
<div class="toolbar"><input id="search" type="search" placeholder="{{ $content['ui']['search'] }}"><select id="genre"><option value="all">{{ $content['ui']['all_genres'] }}</option></select>@if($canEdit)<button id="openMovie">{{ $content['ui']['add_movie'] }}</button><button id="openTier">{{ $content['ui']['add_tier'] }}</button><button id="save" class="primary">{{ $content['ui']['save'] }}</button>@endif<span id="status" class="status"></span></div></header>
<main><div class="stats"><span id="total"></span><span id="ranked"></span></div><div class="board" id="board"></div><section class="unranked"><h2>{{ $content['ui']['unranked'] }}</h2><div class="drop" data-zone="unranked"></div></section>@unless($canEdit)<p class="notice">Рейтинг обновляет владелец. Сервер видит ваш адрес как <strong>{{ $clientIp }}</strong>; для него сейчас нет write-доступа.</p>@endunless</main>
<div class="modal" id="detailModal"><div class="modalbox"><div class="detail-grid"><img id="detailPoster" class="detail-poster" alt="" hidden><div><h2 id="detailTitle"></h2><p id="detailMeta"></p><div class="links" id="detailLinks"></div></div></div><div class="actions"><button type="button" data-close>Закрыть</button>@if($canEdit)<button type="button" class="primary" id="detailEdit">Редактировать</button>@endif</div></div></div>
@if($canEdit)
<div class="modal" id="movieModal"><form class="modalbox" id="movieForm"><h2 id="movieFormTitle">Добавить фильм</h2><div class="fields"><input id="movieTitle" maxlength="200" required placeholder="Название"><div class="field-row"><input id="movieYear" type="number" min="1888" max="2100" placeholder="Год"><input id="movieGenre" maxlength="80" placeholder="Жанр"></div><input id="moviePoster" type="url" maxlength="2048" placeholder="URL постера (необязательно)"><input id="movieLink1" type="url" maxlength="2048" placeholder="Ссылка 1 (необязательно)"><input id="movieLink2" type="url" maxlength="2048" placeholder="Ссылка 2 (необязательно)"></div><div class="actions"><button type="button" data-close>Отмена</button><button class="primary" id="movieSubmit">Добавить фильм</button></div></form></div>
<div class="modal" id="tierModal"><form class="modalbox" id="tierForm"><h2 id="tierFormTitle">Добавить тир</h2><div class="fields"><div class="field-row"><input id="tierLabel" maxlength="12" required placeholder="Метка, например S+"><input id="tierColor" type="color" value="#efc75e" title="Цвет"></div><input id="tierCaption" maxlength="80" placeholder="Подпись, например Шедевр"></div><div class="actions"><button type="button" data-close>Отмена</button><button class="primary" id="tierSubmit">Добавить тир</button></div></form></div>
<div class="modal" id="confirmModal"><div class="modalbox"><h2 id="confirmTitle"></h2><p id="confirmText"></p><div class="actions"><button type="button" data-close>Отмена</button><button type="button" class="danger" id="confirmDelete">Удалить</button></div></div></div>
@endif
<script>
const CAN_EDIT=@json($canEdit),UPDATE_URL=@json(route('movies-tier-list.update')),CSRF=document.querySelector('meta[name="csrf-token"]').content,UI=@json($content['ui']);
let revision=@json($revision),tiers=@json($tiers),movies=@json($movies),dirty=false,pendingDelete=null,editingMovieId=null,editingTierId=null,detailMovieId=null,dragging=false;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const uid=prefix=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
function movieCard(movie){const el=document.createElement('article');el.className=`card${movie.poster_url?' has-poster':''}`;el.dataset.id=movie.id;el.draggable=CAN_EDIT;const info=`<div class="title">${esc(movie.title)}</div><div class="meta">${[movie.year,movie.genre].filter(Boolean).map(esc).join(' · ')}</div>`;el.innerHTML=movie.poster_url?`<img class="poster" src="${esc(movie.poster_url)}" alt="" loading="lazy"><div class="poster-shade">${info}</div>`:info;el.onclick=()=>{if(!dragging)openDetails(movie.id)};if(CAN_EDIT){el.insertAdjacentHTML('beforeend','<div class="movie-actions"><button class="edit-movie" type="button" title="Редактировать фильм">Изм.</button><button class="remove-movie" type="button" title="Удалить фильм">×</button></div>');el.querySelector('.edit-movie').onclick=e=>{e.stopPropagation();openMovieForm(movie.id)};el.querySelector('.remove-movie').onclick=e=>{e.stopPropagation();askDelete('film',movie.id,movie.title)};el.ondragstart=e=>{dragging=true;e.dataTransfer.setData('text/plain',movie.id);requestAnimationFrame(()=>el.style.opacity='.35')};el.ondragend=()=>{el.style.opacity='1';setTimeout(()=>dragging=false,0)}}return el}
function tierSection(tier){const ordered=[...tiers].sort((a,b)=>a.position-b.position),index=ordered.findIndex(item=>item.id===tier.id),first=index===0,last=index===ordered.length-1;const el=document.createElement('section');el.className='tier';el.innerHTML=`<div class="label" style="background:${esc(tier.color)}">${esc(tier.label)}<small>${esc(tier.caption||'')}</small></div>${CAN_EDIT?`<div class="tier-actions"><button class="move-tier move-up" type="button" title="Поднять тир" aria-label="Поднять тир" ${first?'disabled':''}>↑</button><button class="move-tier move-down" type="button" title="Опустить тир" aria-label="Опустить тир" ${last?'disabled':''}>↓</button><button class="edit-tier" type="button" title="Редактировать тир">Изм.</button><button class="remove-tier" type="button" title="Удалить тир">×</button></div>`:''}<div class="drop" data-zone="${esc(tier.id)}"></div>`;if(CAN_EDIT){el.querySelector('.move-up').onclick=()=>moveTier(tier.id,-1);el.querySelector('.move-down').onclick=()=>moveTier(tier.id,1);el.querySelector('.edit-tier').onclick=()=>openTierForm(tier.id);el.querySelector('.remove-tier').onclick=()=>askDelete('tier',tier.id,tier.label)}bindDrop(el.querySelector('.drop'));return el}
function moveTier(id,direction){const ordered=[...tiers].sort((a,b)=>a.position-b.position),index=ordered.findIndex(tier=>tier.id===id),target=index+direction;if(index<0||target<0||target>=ordered.length)return;[ordered[index],ordered[target]]=[ordered[target],ordered[index]];ordered.forEach((tier,position)=>tier.position=position);tiers=ordered;dirty=true;render()}
function orderedMovies(){const order=tiers.map(t=>t.id).concat('unranked');return [...movies].sort((a,b)=>order.indexOf(a.tier)-order.indexOf(b.tier)||a.position-b.position)}
function render(){const board=document.getElementById('board');board.innerHTML='';[...tiers].sort((a,b)=>a.position-b.position).forEach(t=>board.appendChild(tierSection(t)));const unranked=document.querySelector('[data-zone="unranked"]');unranked.innerHTML='';orderedMovies().forEach(movie=>(document.querySelector(`[data-zone="${CSS.escape(movie.tier)}"]`)||unranked).appendChild(movieCard(movie)));document.querySelectorAll('.drop').forEach(zone=>{if(!zone.children.length)zone.innerHTML=`<span class="empty">${esc(UI.empty)}</span>`});genres();filter();stats()}
function bindDrop(zone){if(!CAN_EDIT)return;zone.ondragover=e=>{e.preventDefault();zone.classList.add('dragover')};zone.ondragleave=()=>zone.classList.remove('dragover');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('dragover');const movie=movies.find(item=>item.id===e.dataTransfer.getData('text/plain'));if(movie){movie.tier=zone.dataset.zone;movie.position=zone.querySelectorAll('.card').length;dirty=true;render()}}}
function syncPositions(){document.querySelectorAll('.drop').forEach(zone=>[...zone.querySelectorAll('.card')].forEach((el,index)=>{const movie=movies.find(item=>item.id===el.dataset.id);if(movie){movie.tier=zone.dataset.zone;movie.position=index}}));tiers.forEach((tier,index)=>tier.position=index)}
function genres(){const select=document.getElementById('genre'),selected=select.value,list=[...new Set(movies.map(m=>m.genre).filter(Boolean))].sort();select.innerHTML=`<option value="all">${esc(UI.all_genres)}</option>`+list.map(g=>`<option value="${esc(g)}">${esc(g)}</option>`).join('');select.value=list.includes(selected)?selected:'all'}
function filter(){const q=document.getElementById('search').value.trim().toLowerCase(),g=document.getElementById('genre').value;document.querySelectorAll('.card').forEach(el=>{const movie=movies.find(m=>m.id===el.dataset.id),show=movie&&(!q||movie.title.toLowerCase().includes(q))&&(g==='all'||movie.genre===g);el.classList.toggle('hidden',!show)})}
function stats(){document.getElementById('total').textContent=`Фильмов: ${movies.length}`;document.getElementById('ranked').textContent=`Распределено: ${movies.filter(m=>m.tier!=='unranked').length}`}
function status(text,error=false){const el=document.getElementById('status');el.textContent=text;el.classList.toggle('error',error)}function showModal(id){document.getElementById(id).classList.add('on')}function closeModals(){document.querySelectorAll('.modal').forEach(m=>m.classList.remove('on'))}
function openDetails(id){const movie=movies.find(m=>m.id===id);if(!movie)return;detailMovieId=id;document.getElementById('detailTitle').textContent=movie.title;document.getElementById('detailMeta').textContent=[movie.year,movie.genre].filter(Boolean).join(' · ')||'Без дополнительной информации';const poster=document.getElementById('detailPoster');poster.hidden=!movie.poster_url;poster.src=movie.poster_url||'';document.getElementById('detailLinks').innerHTML=(movie.links||[]).map((url,i)=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Открыть ссылку ${i+1}</a>`).join('')||'<span class="notice">Ссылок нет</span>';showModal('detailModal')}
function openMovieForm(id=null){editingMovieId=id;const movie=movies.find(m=>m.id===id);document.getElementById('movieForm').reset();document.getElementById('movieFormTitle').textContent=movie?'Редактировать фильм':'Добавить фильм';document.getElementById('movieSubmit').textContent=movie?'Сохранить изменения':'Добавить фильм';if(movie){document.getElementById('movieTitle').value=movie.title;document.getElementById('movieYear').value=movie.year||'';document.getElementById('movieGenre').value=movie.genre||'';document.getElementById('moviePoster').value=movie.poster_url||'';document.getElementById('movieLink1').value=movie.links?.[0]||'';document.getElementById('movieLink2').value=movie.links?.[1]||''}closeModals();showModal('movieModal')}
function openTierForm(id=null){editingTierId=id;const tier=tiers.find(t=>t.id===id);document.getElementById('tierForm').reset();document.getElementById('tierColor').value=tier?.color||'#efc75e';document.getElementById('tierFormTitle').textContent=tier?'Редактировать тир':'Добавить тир';document.getElementById('tierSubmit').textContent=tier?'Сохранить изменения':'Добавить тир';if(tier){document.getElementById('tierLabel').value=tier.label;document.getElementById('tierCaption').value=tier.caption||''}closeModals();showModal('tierModal')}
function askDelete(type,id,label){pendingDelete={type,id};document.getElementById('confirmTitle').textContent=type==='tier'?'Удалить тир?':'Удалить фильм?';document.getElementById('confirmText').textContent=type==='tier'?`Тир «${label}» будет удалён. Фильмы из него перейдут в «Не распределено».`:`Фильм «${label}» будет удалён из списка.`;showModal('confirmModal')}
async function save(){syncPositions();status(UI.saving);document.getElementById('save').disabled=true;try{const response=await fetch(UPDATE_URL,{method:'PUT',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':CSRF},body:JSON.stringify({revision,tiers,movies})}),data=await response.json();if(!response.ok)throw new Error(data.message||'Не удалось сохранить');revision=data.revision;dirty=false;status(UI.saved)}catch(error){status(error.message,true)}finally{document.getElementById('save').disabled=false}}
document.getElementById('search').oninput=filter;document.getElementById('genre').onchange=filter;document.querySelectorAll('[data-close]').forEach(button=>button.onclick=closeModals);bindDrop(document.querySelector('[data-zone="unranked"]'));
if(CAN_EDIT){document.getElementById('openMovie').onclick=()=>openMovieForm();document.getElementById('openTier').onclick=()=>openTierForm();document.getElementById('detailEdit').onclick=()=>openMovieForm(detailMovieId);document.getElementById('save').onclick=save;
document.getElementById('movieForm').onsubmit=e=>{e.preventDefault();const values={title:document.getElementById('movieTitle').value.trim(),year:Number(document.getElementById('movieYear').value)||null,genre:document.getElementById('movieGenre').value.trim()||null,poster_url:document.getElementById('moviePoster').value.trim()||null,links:[document.getElementById('movieLink1').value.trim(),document.getElementById('movieLink2').value.trim()].filter(Boolean)};const movie=movies.find(m=>m.id===editingMovieId);if(movie)Object.assign(movie,values);else movies.push({id:uid('movie'),...values,tier:'unranked',position:movies.filter(m=>m.tier==='unranked').length});editingMovieId=null;dirty=true;closeModals();render()};
document.getElementById('tierForm').onsubmit=e=>{e.preventDefault();const values={label:document.getElementById('tierLabel').value.trim(),caption:document.getElementById('tierCaption').value.trim()||null,color:document.getElementById('tierColor').value};const tier=tiers.find(t=>t.id===editingTierId);if(tier)Object.assign(tier,values);else tiers.push({id:uid('tier'),...values,position:tiers.length});editingTierId=null;dirty=true;closeModals();render()};
document.getElementById('confirmDelete').onclick=()=>{if(!pendingDelete)return;if(pendingDelete.type==='film')movies=movies.filter(m=>m.id!==pendingDelete.id);else{tiers=tiers.filter(t=>t.id!==pendingDelete.id);movies.forEach(m=>{if(m.tier===pendingDelete.id)m.tier='unranked'})}pendingDelete=null;dirty=true;closeModals();render()};window.onbeforeunload=e=>{if(dirty){e.preventDefault();e.returnValue=''}}}
render();
</script>
</body>
</html>
