<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Craft Chess</title>
<style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;font:16px system-ui;background:#111827;color:#e5e7eb}main{max-width:1050px;margin:auto;padding:24px}.layout{display:grid;grid-template-columns:minmax(300px,680px) 280px;gap:24px}.board{display:grid;grid-template-columns:repeat(8,1fr);aspect-ratio:1;max-width:680px}.sq{display:grid;place-items:center;font-size:clamp(28px,7vw,70px);cursor:pointer;user-select:none}.light{background:#f0d9b5}.dark{background:#b58863}.selected{box-shadow:inset 0 0 0 5px #facc15}.panel{background:#1f2937;border-radius:12px;padding:18px;height:max-content}button,a{background:#b58863;color:#fff;border:0;border-radius:7px;padding:9px 12px;text-decoration:none;cursor:pointer}.seat{display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-bottom:1px solid #374151}.moves{max-height:350px;overflow:auto;line-height:1.8;color:#d1d5db}.error{color:#fca5a5;min-height:24px}@media(max-width:800px){.layout{grid-template-columns:1fr}.panel{order:-1}}
</style></head><body><main><p><a href="{{ route('chess.index') }}">← Lobby</a></p><div class="layout"><div id="board" class="board"></div><aside class="panel"><h2 id="status">Loading…</h2><div class="seat"><span>♔ <b id="white">Open seat</b></span><button data-color="white">Join</button></div><div class="seat"><span>♚ <b id="black">Open seat</b></span><button data-color="black">Join</button></div><p id="role"></p><div id="error" class="error"></div><h3>Moves</h3><div id="moves" class="moves"></div></aside></div></main>
<script>
const urls={state:@json(route('chess.state',$game)),join:@json(route('chess.join',$game)),move:@json(route('chess.move',$game))};
const token=document.querySelector('meta[name=csrf-token]').content,pieces={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};let state,selected=null;
async function api(url,data){const r=await fetch(url,{method:data?'POST':'GET',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':token},body:data?JSON.stringify(data):null});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.message||'Request failed');return body}
function position(fen){const out={},ranks=fen.split(' ')[0].split('/');ranks.forEach((rank,y)=>{let x=0;for(const c of rank){if(/\d/.test(c))x+=Number(c);else{out['abcdefgh'[x]+(8-y)]=c;x++}}});return out}
function render(s){state=s;document.querySelector('#white').textContent=s.white||'Open seat';document.querySelector('#black').textContent=s.black||'Open seat';document.querySelector('#role').textContent=s.myColor?'You play '+s.myColor:'You are observing';document.querySelector('#status').textContent=s.status==='finished'?(s.result==='draw'?'Draw':s.result+' wins'):s.status==='waiting'?'Waiting for players':(s.fen.split(' ')[1]==='w'?'White':'Black')+' to move';document.querySelectorAll('[data-color]').forEach(b=>b.hidden=!!s[b.dataset.color]);document.querySelector('#moves').textContent=s.moves.map((m,i)=>(i%2?'':`${Math.floor(i/2)+1}. `)+m+(i%2?'\n':' ')).join('');
 const board=document.querySelector('#board'),pos=position(s.fen),flip=s.myColor==='black',files=flip?'hgfedcba':'abcdefgh',ranks=flip?'12345678':'87654321';board.innerHTML='';for(const rank of ranks)for(const file of files){const name=file+rank,el=document.createElement('div');el.className='sq '+(((file.charCodeAt(0)-97+Number(rank))%2)?'light':'dark')+(selected===name?' selected':'');el.textContent=pieces[pos[name]]||'';el.onclick=()=>square(name);board.appendChild(el)}}
async function square(name){if(!state.myColor||state.status!=='playing')return;if(!selected){selected=name;render(state);return}const from=selected;selected=null;try{render(await api(urls.move,{from,to:name,promotion:'q'}));error('')}catch(e){error(e.message);render(state)}}
function error(m){document.querySelector('#error').textContent=m}document.querySelectorAll('[data-color]').forEach(b=>b.onclick=async()=>{try{render(await api(urls.join,{color:b.dataset.color}));error('')}catch(e){error(e.message)}});async function refresh(){try{render(await api(urls.state))}catch(e){error(e.message)}}refresh();setInterval(refresh,2000);
</script></body></html>
